[package]
name = "zkenc-js"
version = "0.2.0"
authors = [ "flyinglimao <hi@limaois.me>" ]
description = "WASM bindings for zkenc-core"
repository = "https://github.com/flyinglimao/zkenc"
categories = ["cryptography", "wasm"]
license = "MIT/Apache-2.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
# zkenc core library only
zkenc-core = { path = "../zkenc-core", default-features = false, features = ["std", "r1cs", "with_curves"] }

# Arkworks for BN254 curve (Circom's default)
ark-bn254 = { git = "https://github.com/arkworks-rs/algebra.git", default-features = false, features = ["std", "curve"] }
ark-ff = { git = "https://github.com/arkworks-rs/algebra.git", default-features = false, features = ["std"] }
ark-ec = { git = "https://github.com/arkworks-rs/algebra.git", default-features = false, features = ["std"] }
ark-serialize = { git = "https://github.com/arkworks-rs/algebra.git", default-features = false, features = ["std"] }
ark-relations = { git = "https://github.com/arkworks-rs/snark.git", default-features = false, features = ["std"] }
ark-std = { git = "https://github.com/arkworks-rs/std.git", default-features = false, features = ["std"] }

# WASM bindings
wasm-bindgen = "0.2"
js-sys = "0.3"
getrandom = { version = "0.2", features = ["js"] }
console_error_panic_hook = { version = "0.1", optional = true }

# Serialization
serde = { version = "1.0", features = ["derive"] }
serde-wasm-bindgen = "0.6"
serde_json = { version = "1.0", features = ["preserve_order"] }

[dev-dependencies]
wasm-bindgen-test = "0.3"

[features]
default = ["console_error_panic_hook"]
