[package]
name = "zkenc-core"
version = "0.1.0"
authors = [ "flyinglimao" ]
description = "An implementation of a witness encryption for QAP"
repository = "https://github.com/flyinglimao/zkenc"
documentation = "https://flyinglimao.github.io/zkenc/"
categories = ["cryptography"]
license = "MIT/Apache-2.0"
edition = "2021"

[dependencies]
# Arkworks algebra - 數學基礎庫 (統一使用 git)
ark-ff = { git = "https://github.com/arkworks-rs/algebra.git", default-features = false }
ark-ec = { git = "https://github.com/arkworks-rs/algebra.git", default-features = false }
ark-serialize = { git = "https://github.com/arkworks-rs/algebra.git", default-features = false, features = [ "derive" ] }
ark-poly = { git = "https://github.com/arkworks-rs/algebra.git", default-features = false }
ark-std = { git = "https://github.com/arkworks-rs/std.git", default-features = false }

# Arkworks SNARK - R1CS 與 SNARK 抽象層
ark-relations = { git = "https://github.com/arkworks-rs/snark.git", default-features = false }
ark-snark = { git = "https://github.com/arkworks-rs/snark.git", default-features = false }

# Arkworks gadgets - 可選功能（電路元件）
ark-r1cs-std = { git = "https://github.com/arkworks-rs/r1cs-std.git", default-features = false, optional = true }
ark-crypto-primitives = { git = "https://github.com/arkworks-rs/crypto-primitives.git", default-features = false, features = [ "snark", "sponge" ] }

# 輔助工具
tracing = { version = "0.1", default-features = false, features = ["attributes"], optional = true }
educe = { version = "0.6.0", default-features = false, features = [ "Clone" ], optional = true }

# 並行支援（optional，wasm 不使用）
rayon = { version = "1", optional = true }

# WASM 支援
wasm-bindgen = { version = "0.2", optional = true }
getrandom = { version = "0.2", features = ["js"], optional = true }

# Optional concrete curves for integration tests/examples
# BN254 (alt_bn128) - used by Circom/snarkjs
ark-bn254 = { git = "https://github.com/arkworks-rs/algebra.git", default-features = false, optional = true, features = ["curve"] }
# BLS12-381 - for non-Circom tests
ark-bls12-381 = { git = "https://github.com/arkworks-rs/algebra.git", default-features = false, optional = true, features = ["curve"] }

# Serialization (for test fixtures)
serde = { version = "1.0", features = ["derive"], optional = true }
serde_json = { version = "1.0", optional = true }
bincode = { version = "1.3", optional = true }

[lib]
crate-type = ["cdylib", "rlib"]

[features]
default = ["std"]

# 標準庫支援
std = [
    "ark-ff/std",
    "ark-ec/std",
    "ark-poly/std",
    "ark-relations/std",
    "ark-crypto-primitives/std",
    "ark-std/std",
]

# 並行計算（僅 native）
parallel = [
    "std",
    "ark-ff/parallel",
    "ark-poly/parallel",
    "ark-ec/parallel",
    "ark-crypto-primitives/parallel",
    "ark-std/parallel",
    "rayon",
]

# R1CS gadgets 支援
r1cs = [
    "ark-crypto-primitives/constraints",
    "ark-r1cs-std",
    "tracing",
    "educe",
]

# WASM 支援
wasm = [
    "wasm-bindgen",
    "getrandom",
]

# 除錯追蹤
print-trace = ["ark-std/print-trace"]

# Optional feature to enable tests/examples that require a pairing curve
with_curves = ["ark-bls12-381", "ark-bn254", "std", "r1cs"]

# Test fixtures support (for loading serialized circuits)
test_fixtures = ["serde", "serde_json", "bincode", "with_curves"]
