blank_issues_enabled: true
contact_links:
  - name: Documentation
    url: https://zkenc.limaois.me
    about: Check out the documentation for guides and examples
  - name: Discussions
    url: https://github.com/flyinglimao/zkenc/discussions
    about: Ask questions and discuss ideas with the community
