[package]
name = "zkenc-cli"
version = "0.1.0"
authors = [ "flyinglimao <hi@limaois.me>" ]
description = "CLI tool for zkenc-core"
repository = "https://github.com/flyinglimao/zkenc"
categories = ["cryptography", "command-line-utilities"]
license = "MIT/Apache-2.0"
edition = "2021"

[lib]
name = "zkenc_cli"
path = "src/lib.rs"

[[bin]]
name = "zkenc"
path = "src/main.rs"

[dependencies]
zkenc-core = { path = "../zkenc-core", features = ["std", "parallel"] }

# CLI 相關
clap = { version = "4.5", features = ["derive"] }
anyhow = "1.0"

# 序列化/反序列化
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

# 檔案操作
hex = "0.4"

# AES encryption
aes-gcm = "0.10"
aes = "0.8"
ctr = "0.9"
cipher = { version = "0.4", features = ["std"] }
rand = "0.8"

# Circom integration (placeholder for now, will add proper integration in Phase 2/3)
# ark-circom will be added when we implement witness generation
#
# Note: Full integration deferred due to arkworks version conflicts:
# - zkenc-core uses git versions (0.5 pre-release)
# - ark-circom/stable arkworks use crates.io 0.4
# This will be resolved in future when versions stabilize
