[package]
name = "zkenc-cli"
version = "0.1.0"
authors = [ "flyinglimao <hi@limaois.me>" ]
description = "CLI tool for zkenc-core"
repository = "https://github.com/flyinglimao/zkenc"
categories = ["cryptography", "command-line-utilities"]
license = "MIT OR Apache-2.0"
edition = "2021"

[lib]
name = "zkenc_cli"
path = "src/lib.rs"

[[bin]]
name = "zkenc"
path = "src/main.rs"

[dependencies]
zkenc-core = { path = "../zkenc-core", features = ["std", "parallel"] }

# CLI 相關
clap = { version = "4.5", features = ["derive"] }
anyhow = "1.0"

# 序列化/反序列化
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
bincode = "1.3"

# 檔案操作
hex = "0.4"

# Arkworks - matching zkenc-core versions
ark-bls12-381 = { git = "https://github.com/arkworks-rs/algebra.git", features = ["curve"] }
ark-bn254 = { git = "https://github.com/arkworks-rs/algebra.git", features = ["curve"] }
ark-ff = { git = "https://github.com/arkworks-rs/algebra.git" }
ark-relations = { git = "https://github.com/arkworks-rs/snark.git" }
ark-serialize = { git = "https://github.com/arkworks-rs/algebra.git" }
ark-std = { git = "https://github.com/arkworks-rs/std.git" }

# AES encryption
aes-gcm = "0.10"
aes = "0.8"
ctr = "0.9"
cipher = { version = "0.4", features = ["std"] }
rand = "0.8"

# Circom integration
# Note: ark-circom git version has internal dependency conflicts:
# - Its Cargo.toml uses crates.io ark-bn254 0.5.0 (for dependencies)
# - But git versions for dev-dependencies
# - crates.io ark-bn254 0.5.0 is incompatible with git ark-ec (missing ZeroFlag trait)
# 
# Options:
# 1. Wait for ark-circom to fully migrate to git versions OR crates.io 0.5 stable release
# 2. Fork ark-circom and fix dependency sources
# 3. Use separate architecture (Node.js circom + Rust zkenc-core)
#
# For now, continuing with Phases 4-5 (AES + CLI) without full Circom integration
